<div class="row">
    <form class="large-4 columns alert-aware" method="POST" action="#">
        <label for="login-email">Username</label>
        <input type="text" name="username" id="login-email" autocomplete="off" />

        <label for="login-password">Password</label>
        <input type="password" name="password" id="login-password" />

        <p><input type="submit" class="button radius" value="Sign In"/></p>
    </form>
</div>