<div class="row alert-aware">
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Options</th>
                <th><a href="/administration/attribute/new" class="tiny radius"> <i class="icon-plus-sign"></i> </a></th>
            </tr>
        </thead>
        <tbody>
<?php foreach ($this->attributes as $attribute) : ?>
            <tr>
                <td>
                    <?php echo $attribute->getLabel(); ?>
                </td>
                <td>
                    <?php echo $this->attribute_map[$attribute->getType()]; ?>
                </td>
                <td>
    <?php 
        switch ($attribute->getType()) {
            case Falcon\Product\Attribute\Attribute::TYPE_TEXT:
            case Falcon\Product\Attribute\Attribute::TYPE_TEXTAREA:
                echo '<em>na</em>';
                break;
            case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
            case Falcon\Product\Attribute\Attribute::TYPE_SET_RADIO:
                case Falcon\Product\Attribute\Attribute::TYPE_SET_CHECKBOX:
                if ($attribute->hasChildren()) {
                    foreach ($attribute->getChildren() as $child) {
                                echo '<span class="radius secondary label">' . $child->getLabel() . '</span> &nbsp;';
                    }
                }
                break;
        } //switch
    ?>
                </td>
                <td>
                    <a href="/administration/attribute/edit/<?php echo $attribute->getId(); ?>" class="tiny radius"> <i class="icon-pencil"></i> </a>
                </td>
            </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>
