<?php
$product = $this->product;
$attributes = $this->attributes;
?>
<h3><?php echo $product->get('name'); ?> <small><a href="/administration/product/edit/<?php echo $product->getUUID(); ?>" class=""><i class="icon-pencil"></i></a></small></h3>
<div class="row">
    <div class="large-2 columns">
        <label for="name" class="inline">Year:</label>
    </div>
    <div class="large-4 columns">
        <?php echo $this->isempty($product->get('year')); ?>
    </div>
    <div class="large-6 columns"></div>
</div>
<div class="row">
    <div class="large-2 columns">
        <label for="name" class="inline">Designer:</label>
    </div>
    <div class="large-10 columns">
        <?php echo $this->isempty($product->get('designer')); ?>
    </div>
</div>
<div class="row">
    <div class="large-2 columns">
        <label for="name" class="inline">Publisher:</label>
    </div>
    <div class="large-10 columns">
        <?php echo $this->isempty($product->get('publisher')); ?>
    </div>
</div>
<div class="row">
    <div class="large-2 columns">
        <label for="name" class="inline">SKU:</label>
    </div>
    <div class="large-4 columns">
        <?php echo $this->isempty($product->get('sku')); ?>
    </div>
    <div class="large-6 columns"></div>
</div>
<div class="row">
    <div class="large-2 columns">
        <label for="name" class="inline">UPC:</label>
    </div>
    <div class="large-4 columns">
        <?php echo $this->isempty($product->get('upc')); ?>
    </div>
    <div class="large-6 columns"></div>
</div>
<div class="row">
    <div class="large-2 columns">
        <label for="name" class="inline">MSRP:</label>
    </div>
    <div class="large-4 columns">
        <?php echo $this->isempty($product->get('msrp')); ?>
    </div>
    <div class="large-6 columns"></div>
</div>
<?php foreach ($this->attributes as $attribute) : ?>
<div class="row attributes">
    <div class="large-2 columns">
        <label for="name" class="inline"><?php echo $attribute->getLabel() ?>:</label>
    </div>
    <div class="large-10 columns">
    <?php
        $attributeId = $attribute->getId();
        $val = null;
        switch ($attribute->getType()) {
            case Falcon\Product\Attribute\Attribute::TYPE_TEXT:
            case Falcon\Product\Attribute\Attribute::TYPE_TEXTAREA:
                $text = $product->getAttribute($attribute->getId());
                echo $this->isempty($text); 
                break;
            case Falcon\Product\Attribute\Attribute::TYPE_URL:
                $url = $product->getAttribute($attribute->getId());
                if (!empty($url)) {
                    printf('<a href="%s" target="_blank">%s</a>', htmlspecialchars($url), htmlspecialchars($url));
                } 
                break;
                
            case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
                if ($attribute->hasChildren()) {
                    foreach ($attribute->getChildren() as $child) {
                        if ($child->getId() == $product->getAttribute($attributeId)) {
                            printf('<span class="radius secondary label">%s</span>', $child->getLabel());
                        }
                    }
                }
                break;
            case Falcon\Product\Attribute\Attribute::TYPE_SET_RADIO:
                if ($attribute->hasChildren()) {
                    foreach ($attribute->getChildren() as $child) {
                        if ($child->getId() == $product->getAttribute($attributeId)) {
                            printf('<span class="radius secondary label">%s</span>', $child->getLabel());
                        }
                    }
                }
                break;
            case Falcon\Product\Attribute\Attribute::TYPE_SET_CHECKBOX:
                if ($attribute->hasChildren()) {
                    foreach ($attribute->getChildren() as $child) {
                        if ($product->getAttribute($child->getId())) {
                            printf('<span class="radius secondary label">%s</span> &nbsp;', $child->getLabel());
                        }
                    }
                }
                break;
            
            case Falcon\Product\Attribute\Attribute::TYPE_CHECKBOX:
                $selected = $product->getAttribute($attributeId) == 1 ? 'Yes' : 'No';
                printf('<span class="radius secondary label">%s</span>', $selected);
                break;
                            
            
        }
    ?>
    </div>
</div>
<?php endforeach; ?>

<h4>Images</h4>
<div class="row">
    
</div>
