<?php 
$product = $this->product;
?>
<form class="alert-aware" method="post" action="<?php echo $this->basePath('administration/product/edit')?>">
    <input type="hidden" name="product[id]" value="<?php echo $product->getId(); ?>" />
    <input type="hidden" name="product[uuid]" value="<?php echo $product->getUUID(); ?>" />
    <fieldset>
        <legend><h3>Edit Product</h3></legend>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Title (required):</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[name]" value="<?php echo $product->get('name'); ?>" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Year:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[year]" value="<?php echo $product->get('year'); ?>" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Designer:</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[designer]" value="<?php echo $product->get('designer'); ?>" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Publisher:</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[publisher]" value="<?php echo $product->get('publisher'); ?>" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">SKU:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[sku]" value="<?php echo $product->get('sku'); ?>" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">UPC:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[upc]" value="<?php echo $product->get('upc'); ?>" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">MSRP:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[msrp]" value="<?php echo $product->get('msrp'); ?>" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <?php foreach ($this->attributes as $attribute) : ?>
        <div class="row attributes">
            <div class="large-2 columns">
                <label for="name" class="inline"><?php echo $attribute->getLabel() ?>:</label>
            </div>
            <div class="large-10 columns">
            <?php 
                switch ($attribute->getType()) {
                    case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
                        echo '<select name="attribute[' . $attribute->getId() . ']">';
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                $selected = '';
                                if ($child->getId() == $product->getAttribute($attribute->getId())) {
                                    $selected = ' selected="selected"';
                                }
                                printf('<option value="%s"%s>%s</option>', $child->getId(), $selected, $child->getLabel());
                            }
                        }
                        echo '</select>';
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_SET_RADIO:
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                $selected = '';
                                 if ($child->getId() == $product->getAttribute($child->getId())) {
                                     $selected = ' checked="checked"';
                                 }
                                printf('<input type="radio" name=attribute[%s] value="%s" %s /> %s &nbsp;&nbsp;', $attribute->getId(), $child->getId(), $selected, $child->getLabel());
                            }
                        }
                        break;
                        
                    case Falcon\Product\Attribute\Attribute::TYPE_SET_CHECKBOX:
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                $selected = '';
                                if ($product->getAttribute($child->getId())) {
                                    $selected = 'checked="checked"';
                                }
                                printf('<input type="checkbox" name=attribute[%s] value="1" %s /> %s &nbsp;&nbsp;', $child->getId(), $selected, $child->getLabel());
                            }
                        }
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_CHECKBOX:
                        $selected = $product->getAttribute($attribute->getId()) == 1 ? 'checked="checked"' : '';
                        printf('<input type="checkbox" name=attribute[%s] value="1" %s /> %s &nbsp;&nbsp;', $attribute->getId(), $selected, $attribute->getLabel());
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_TEXTAREA:
                        printf('<textarea name="attribute[%s]">%s</textarea>', $attribute->getId(), htmlspecialchars($product->getAttribute($attribute->getId())));
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_TEXT:
                    case Falcon\Product\Attribute\Attribute::TYPE_URL:
                        printf('<input type="text" name="attribute[%s]" value="%s" />', $attribute->getId(), htmlspecialchars($product->getAttribute($attribute->getId())));
                        break;
                }
            ?>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline"></label>
            </div>
            <div class="large-10 columns">
                <button id="submit" class="button radius">Save</button>
                <button id="cancel" class="button radius secondary" onclick="parent.location.href='/administration/product/index'; return false;">Cancel</button>
            </div>
        </div>
    </fieldset>
</form>
<style>
    .attributes select {
        width: 50%;
    }
</style>