<form class="form-data alert-aware" method="post" action="<?php echo $this->basePath('administration/product/import')?>">
    <fieldset>
        <legend><h3>Product Import</h3></legend>
        <h5 class="subheader">Main Fields: </h5>
            <ul class="inline-list">
                <li>SKU</li>
                <li>Name</li>
                <li>Year</li>
                <li>Designer</li>
                <li>Publisher</li>
                <li>UPC</li>
                <li>MSRP</li>
            </ul> 
        <h5 class="subheader">Attributes: </h5>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
<?php
    foreach ($this->attributeCollection as $attribute) {
        echo '<tr>';
        echo '<td>' . $attribute->getLabel() . '</td>';
        switch ($attribute->getType()) {
            case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
                echo '<td>';
                echo 'select';
                echo '</td>';
                echo '<td>';
                foreach ($attribute->getOptions() as $option) {
                    echo '<span class="label secondary radius">' . $option . '</span> ';
                }
                echo '</td>';
                break;

            case Falcon\Product\Attribute\Attribute::TYPE_SET:
                $children = $attribute->getChildren();
                $type = $children[0]->getType() == Falcon\Product\Attribute\Attribute::TYPE_CHECKBOX ? 'checkbox' : 'radio';
                echo '<td>' . $type . '</td>';
                echo '<td>';
                foreach ($children as $child) {
                    echo '<span class="label secondary radius">' . $child->getLabel() . '</span> ';
                }
                echo '</td>';
                break;
                
                
            default:
                echo '<td>text</td><td></td>';
                break;
        }
        echo '</tr>';
    }
?>
            </tbody>
        </table>
        <p> <a href="<?php echo $this->basePath('administration/product/import-template')?>" target="_blank">Download import template here.</a> </p>
        <input type="file" name="file" />
        <button class="radius">Submit</button>
    </fieldset>
</form>