<form class="form-data alert-aware" method="post" action="<?php echo $this->basePath('administration/product/import')?>">
    <fieldset>
        <legend><h3>Product Import</h3></legend>
        <h5 class="subheader">Main Fields: </h5>
            <ul class="inline-list">
                <li>SKU</li>
                <li>Name</li>
                <li>Year</li>
                <li>Designer</li>
                <li>Publisher</li>
                <li>UPC</li>
                <li>MSRP</li>
            </ul> 
        <h5 class="subheader">Current Attributes: </h5>
        <div class="row">
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
        <?php foreach ($this->attributeCollection as $attribute) : ?>
                    <tr>
                        <td>
                            <?php echo $attribute->getLabel(); ?>
                        </td>
                        <td>
                            <?php echo $this->attribute_map[$attribute->getType()]; ?>
                        </td>
                        <td>
            <?php 
                switch ($attribute->getType()) {
                    case Falcon\Product\Attribute\Attribute::TYPE_TEXT:
                    case Falcon\Product\Attribute\Attribute::TYPE_TEXTAREA:
                        echo '<em>na</em>';
                        break;
                    case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
                    case Falcon\Product\Attribute\Attribute::TYPE_SET_RADIO:
                        case Falcon\Product\Attribute\Attribute::TYPE_SET_CHECKBOX:
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                        echo '<span class="radius secondary label">' . $child->getLabel() . '</span> &nbsp;';
                            }
                        }
                        break;
                } //switch
            ?>
                        </td>
                    </tr>
        <?php endforeach; ?>
                </tbody>
            </table>
        </div>


        <h5>How to start import</h5>
        <p>1. Prepare an import file. <a href="<?php //echo $this->basePath('administration/product/import-template')?>" target="_blank" style="text-decoration:line-through">Download import template here.</a> Use Google Spreadsheet for now.</p>
        <p>2. Upload the import file <input type="file" name="file" /></p>
        <button class="radius">Submit</button>
    </fieldset>
</form>
<script>
    function onFormDataSuccess(data){
        pushAlert('Processed: ' + data.result + ' records', 'success');
    }
</script>