<?php
$categoryAttr = $this->attributes->findByName('Category');
$categories = array();
foreach ($categoryAttr->getChildren() as $child) {
    $categories[$child->getId()] = $child->getLabel();
}
?>
<div class="row alert-aware">
    <h5>Products</h5>
    <table width="100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>&nbsp;</th>
                <th>SKU</th>
                <th>Category</th>
                <th>Publisher</th>
                <th><a href="/administration/product/new" class="tiny radius"> <i class="icon-plus-sign"></i> </a></th>
            </tr>
        </thead>
        <tbody>
    <?php if (empty($this->products)) : ?>
        <tr>
          <td colspan="6">
              No products. <a href="/administration/product/new" class="tiny radius"> <i class="icon-plus-sign"></i> add </a>
          </td>
        </tr>
    <?php endif; ?>
    <?php foreach ($this->products as $product) : ?>
        <tr>
            <td>
                <a href="/administration/product/detail/<?php echo $product->getUUID(); ?>" class="tiny radius secondary"><?php echo $product->get('name');?></a>
            </td>
            <td>
                <a href="<?php echo $product->getMainImage($this->basePath())?>"><i class="icon-picture"></i></a>
            </td>
            <td>
                <?php echo $product->get('sku');?>
            </td>
            <td>
                <?php
                    $attrId = $product->getAttribute($categoryAttr->getId());
                    echo $categories[$attrId];
                ?>
            </td>
            <td>
                <?php echo $this->isempty($product->get('publisher'), '-'); ?>
            </td>
            <td>
                <a href="/administration/product/edit/<?php echo $product->getUUID(); ?>" class="tiny radius"> <i class="icon-pencil"></i> </a>
                <a onclick="return confirm('Are you sure?')" href="/administration/product/remove/<?php echo $product->getUUID(); ?>" class="tiny radius"> <i class="icon-remove"></i> </a>
            </td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
</div>