<form class="alert-aware" method="post" action="#">
    <input type="hidden" name="product[id]" value="" />
    <input type="hidden" name="product[uuid]" value="" />
    <fieldset>
        <legend><h3>New Product</h3></legend>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Title (required):</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[name]" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Year:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[year]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Designer:</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[designer]" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Publisher:</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[publisher]" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">SKU:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[sku]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">UPC:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[upc]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">MSRP:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[msrp]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <?php foreach ($this->attributes as $attribute) : ?>
        <div class="row attributes">
            <div class="large-2 columns">
                <label for="name" class="inline"><?php echo $attribute->getLabel() ?>:</label>
            </div>
            <div class="large-10 columns">
            <?php 
                switch ($attribute->getType()) {
                    case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
                        echo '<select name="attribute[' . $attribute->getId() . ']">';
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                printf('<option value="%s">%s</option>', $child->getId(), $child->getLabel());
                            }
                        }
                        echo '</select>';
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_SET_RADIO:
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                printf('<input type="radio" name=attribute[%s] value="%s" /> %s &nbsp;&nbsp;', $attribute->getId(), $child->getId(), $child->getLabel());
                            }
                        }
                        break;
                        
                    case Falcon\Product\Attribute\Attribute::TYPE_SET_CHECKBOX:
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                printf('<input type="checkbox" name=attribute[%s] value="1" /> %s &nbsp;&nbsp;', $child->getId(), $child->getLabel());
                            }
                        }
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_CHECKBOX:
                        printf('<input type="checkbox" name=attribute[%s] value="1" /> %s &nbsp;&nbsp;', $attribute->getId(), $attribute->getLabel());
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_TEXTAREA:
                        echo '<textarea name="attribute[' . $attribute->getId() . ']"></textarea>';
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_TEXT:
                    case Falcon\Product\Attribute\Attribute::TYPE_URL:
                        echo '<input type="text" name="attribute[' . $attribute->getId() . ']" />';
                        break;
                }
            ?>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline"></label>
            </div>
            <div class="large-10 columns">
                <button id="submit" class="button radius">Save</button>
                <button id="cancel" class="button radius secondary" onclick="parent.location.href='/administration/product/index'; return false;">Cancel</button>
            </div>
        </div>
    </fieldset>
</form>
<style>
    .attributes select {
        width: 50%;
    }
</style>