<form class="alert-aware" method="post" action="#">
    <input type="hidden" name="product[id]" value="" />
    <input type="hidden" name="product[uuid]" value="" />
    <fieldset>
        <legend><h3>New Product</h3></legend>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Title (required):</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[name]" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Year:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[year]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Designer:</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[designer]" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">Publisher:</label>
            </div>
            <div class="large-10 columns">
                <input type="text" name="product[publisher]" />
            </div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">SKU:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[sku]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">UPC:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[upc]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline">MSRP:</label>
            </div>
            <div class="large-4 columns">
                <input type="text" name="product[msrp]" />
            </div>
            <div class="large-6 columns"></div>
        </div>
        <?php foreach ($this->attributes as $attribute) : ?>
        <div class="row attributes">
            <div class="large-2 columns">
                <label for="name" class="inline"><?php echo $attribute->getLabel() ?>:</label>
            </div>
            <div class="large-10 columns">
            <?php 
                switch ($attribute->getType()) {
                    case Falcon\Product\Attribute\Attribute::TYPE_SELECT:
                        echo '<select name="attribute[' . $attribute->getId() . ']">';
                        foreach ($attribute->getOptions() as $option) {
                            echo '<option value="' . $option . '">' . $option . '</option>';
                        }
                        echo '</select>';
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_SET:
                        if ($attribute->hasChildren()) {
                            foreach ($attribute->getChildren() as $child) {
                                //for now we assume that set may have only radio or checkbox
                                if ($child->getType() == Falcon\Product\Attribute\Attribute::TYPE_RADIO) {
                                    $type = 'radio';
                                    $id = $attribute->getId();
                                    $val = $child->getId();
                                } else {
                                    $type = 'checkbox';
                                    $id = $child->getId();
                                    $val = 1;
                                }
                                echo '<input type="'.$type.'" name="attribute['. $id .']" value="'.$val.'" /> ';
                                echo $child->getLabel() . '&nbsp;&nbsp;';
                            }
                        }
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_TEXTAREA:
                        echo '<textarea name="attribute[' . $attribute->getId() . ']"></textarea>';
                        break;

                    case Falcon\Product\Attribute\Attribute::TYPE_TEXT:
                        echo '<input type="text" name="attribute[' . $attribute->getId() . ']" />';
                        break;
                }
            ?>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="row">
            <div class="large-2 columns">
                <label for="name" class="inline"></label>
            </div>
            <div class="large-10 columns">
                <button id="submit" class="button radius">Save</button>
                <button id="cancel" class="button radius" onclick="parent.location.href='/administration/product/index'; return false;">Cancel</button>
            </div>
        </div>
    </fieldset>
</form>
<style>
    .attributes select {
        width: 50%;
    }
</style>