<?php
$auth = $this->getHelperPluginManager()->getServiceLocator()->get('ZendAuthService');
$html = '';
if ($auth->hasIdentity()) {
    $routeMatch = $controller = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
    if ($routeMatch) {

        $allMenus = array(
            'left' => array(
                array('label' => 'Products', 'url' => '/administration/product/index', 'sub' => array(
                    array('label' => 'List', 'url' => '/administration/product/index'),
                    array('label' => 'New', 'url' => '/administration/product/new'),
                    array('label' => 'Import', 'url' => '/administration/product/import')
                )),
                array('label' => 'Attributes', 'url' => '/administration/attribute/index', 'sub' => array(
                    array('label' => 'List', 'url' => '/administration/attribute/index'),
                    array('label' => 'New', 'url' => '/administration/attribute/new'),
                )),
                
            ),
            'right' => array(
                array('label' => 'Logout', 'url' => '/logout')
            )
        );

        foreach ($allMenus as $placement => $menus) {
            foreach ($menus as $menu) {
                $html .= '<ul class="'.$placement.'">';
                $html .= '<li class="divider"></li>';
                $html .= '<li'.(isset($menu['sub']) ? ' class="has-dropdown"' : '').'>';
                $html .= '<a href="' . $this->basePath($menu['url']) . '">' . $menu['label'] . '</a>';
                if (isset($menu['sub'])) {
                    $html .= '<ul class="dropdown">';
                    foreach ($menu['sub'] as $subItems) {
                        $html .= '<li class="divider"></li>';
                        $html .= '<li class=""><a href="'.$subItems['url'].'">' . $subItems['label'] . '</a></li>';
                    }
                    $html .= '</ul>';
                }
                $html .= '</li>';
                $html .= '</ul>';
            }
        }
    }
}
?>
<nav class="top-bar">
    <ul class="title-area">
        <li class="name">
            <h1><a href="<?php echo $this->basePath('/administration') ?>">Admin Home</a></h1>
        </li>
        <?php if ($html) :?>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        <?php endif; ?>
    </ul>
    <?php if ($html) :?>
    <section class="top-bar-section">
        <?php echo $html; ?>
    </section>
    <?php endif; ?>
</nav>